server:
  port: 8769
spring:
  application:
    name: edge-server
zuul:
  routes:
    api-a:
      path: /services/search/**
      serviceId: service-ribbon
    api-b:
      path: /services/comment/**
      serviceId: service-feign

eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8761/eureka/
      defaultZone: ${eureka.service.uri:http://micros-discovery:8761}/eureka/
