server:
  port: 8769
spring:
  application:
    name: edge-server
zuul:
  routes:
    api-a:
      path: /services/search/**
      serviceId: service-ribbon
    api-b:
      path: /services/comment/**
      serviceId: service-feign
