server:
  port: 8764
spring:
  application:
    name: service-ribbon

    
eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8761/eureka/
      defaultZone: ${eureka.service.uri:http://micros-discovery:8761}/eureka/
