server:
  port: 8765
spring:
  application:
    name: service-feign

eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8761/eureka/
      defaultZone: ${eureka.service.uri:http://micros-discovery:8761}/eureka/
    